#ifndef PORT_CFG_H_
#define PORT_CFG_H_


/*PORTA MODE*/
#define PORTA_PIN0_MODE   PIN_OUT_LOW//PIN_OUT_LOW
#define PORTA_PIN1_MODE   PIN_OUT_LOW//PIN_OUT_LOW
#define PORTA_PIN2_MODE   PIN_OUT_LOW//PIN_IN_FLOAT
#define PORTA_PIN3_MODE   PIN_OUT_LOW//PIN_IN_PULLUP
#define PORTA_PIN4_MODE   PIN_OUT_LOW//PIN_IN_FLOAT
#define PORTA_PIN5_MODE   PIN_OUT_LOW//PIN_IN_FLOAT
#define PORTA_PIN6_MODE   PIN_OUT_LOW//PIN_IN_FLOAT
#define PORTA_PIN7_MODE   PIN_OUT_LOW//PIN_IN_FLOAT
/*PORTB MODE*/     		  //
#define PORTB_PIN0_MODE	  PIN_OUT_LOW//PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN1_MODE   PIN_OUT_LOW//PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN2_MODE	  PIN_OUT_LOW//PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN3_MODE   PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN4_MODE   PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN5_MODE   PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN6_MODE   PIN_IN_FLOAT	//PIN_OUT_LOW
#define PORTB_PIN7_MODE   PIN_IN_FLOAT	//PIN_OUT_LOW
/*PORTC MODE*/
#define PORTC_PIN0_MODE   PIN_OUT_LOW
#define PORTC_PIN1_MODE   PIN_OUT_LOW
#define PORTC_PIN2_MODE   PIN_OUT_LOW
#define PORTC_PIN3_MODE   PIN_OUT_LOW  
#define PORTC_PIN4_MODE   PIN_IN_FLOAT  
#define PORTC_PIN5_MODE   PIN_IN_FLOAT  
#define PORTC_PIN6_MODE   PIN_IN_FLOAT  
#define PORTC_PIN7_MODE   PIN_IN_FLOAT  
/*PORTD MODE*/				  
#define PORTD_PIN0_MODE   PIN_IN_FLOAT
#define PORTD_PIN1_MODE   PIN_IN_FLOAT
#define PORTD_PIN2_MODE   PIN_IN_FLOAT
#define PORTD_PIN3_MODE   PIN_IN_FLOAT
#define PORTD_PIN4_MODE   PIN_IN_FLOAT
#define PORTD_PIN5_MODE   PIN_IN_FLOAT
#define PORTD_PIN6_MODE   PIN_IN_FLOAT
#define PORTD_PIN7_MODE   PIN_IN_FLOAT
 

#endif